name: Generate Matches

on:
  schedule:
    # 4:00 AM GMT+3 = 01:00 UTC
    - cron: "0 1 * * *"
  workflow_dispatch:  # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 rapidfuzz pytz

      - name: Run script
        run: |
          python main.py > matches.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add matches.txt
          git commit -m "Update matches.txt [skip ci]" || echo "No changes to commit"
          git push
