name: Generate M3U8 per Match

on:
  schedule:
    - cron: "0 * * * *"   # every 1 hour
  workflow_dispatch:       # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests rapidfuzz

      - name: Run script
        run: python merge.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add streams/
          git commit -m "Update streams folder [skip ci]" || echo "No changes to commit"
          git push
